#!/bin/bash

# ../../../src/gschemtoxschem.awk /usr/share/lepton-eda/sym/connector/connector26-1.sym > connector26-1.sym



for file in /usr/share/lepton-eda/sym/*/*.sym
do
  ../../../src//gschemtoxschem.awk $file > `basename $file`
done


