/*************************************************************/
/* Generated by scconfig - DO NOT EDIT - will be overwritten */
/* Source: config.h.in; to regenerate run ./configure        */
/*************************************************************/

/* Define this var if cairo is available and is to be used */
#define HAS_CAIRO 1

/* Define this var if Xlib's xcb is available */
#define HAS_XCB 1

/* Define this var if dup2(2) is available */
#define HAS_DUP2 1

/* Define this var if popen(3) is available */
#define HAS_POPEN 1

/* Define this var if popen(3) is not available but fork(2) and pipe(2) are available */
/*#undef HAS_PIPE */

#define PREFIX               "/usr/local"
#define XSCHEM_LIBRARY_PATH  "~/.xschem/xschem_library:/usr/local/share/xschem/xschem_library/devices:/usr/local/share/doc/xschem/examples:/usr/local/share/doc/xschem/ngspice:/usr/local/share/doc/xschem/logic:/usr/local/share/doc/xschem/xschem_simulator:/usr/local/share/doc/xschem/generators:/usr/local/share/doc/xschem/binto7seg:/usr/local/share/doc/xschem/pcb:/usr/local/share/doc/xschem/rom8k"
#define USER_CONF_DIR        "~/.xschem"
#define XSCHEM_SHAREDIR      PREFIX "/share/xschem"

/* Extra includes required by the detected libs (may be empty): */

#define _XOPEN_SOURCE


