#!/bin/sh

root_file=/home/schippes/xschem-repo/trunk/doc/xschem_man/xschem_man.html
tmpdir=__tmp__

mkdir -p $tmpdir
cp $root_file \
   $(grep  '<li>.*href' $root_file \
     | grep -v '/video_tutorials/' \
     | sed 's/^.*href *= *"//' \
     | sed 's/" *>.*//') \
   $tmpdir
cp *.png $tmpdir
cd $tmpdir
sed -i '/<img/s/>/ width="640">/' *.html

htmldoc --top 10mm --bottom 10mm --right 10mm --left 10mm \
  --webpage --linkcolor blue  --footer ..1 --header ..h -t pdf -f ../xschem_man.pdf \
   $root_file \
   $(grep  '<li>.*href' $root_file \
     | grep -v '/video_tutorials/' \
     | sed 's/^.*href *= *"//' \
     | sed 's/" *>.*//')
  

echo "----"
echo $root_file
echo $(grep  '<li>.*href' $root_file \
     | grep -v '/video_tutorials/' \
     | sed 's/^.*href *= *"//' \
     | sed 's/" *>.*//')

cd ..

rm -rf $tmpdir

