/*************************************************************/
/* Generated by scconfig - DO NOT EDIT - will be overwritten */
/* Source: config.h.in; to regenerate run ./configure        */
/*************************************************************/

/* Define this var if libjpeg is available and is to be used */
/* #define HAS_LIBJPEG 1 */

/* Define to 1 if cairo is available and is to be used */
/* #define HAS_CAIRO 1
#define CAIRO_WIN32_STATIC_BUILD 1 */

/* Define to 1 if Xlib's xcb is available */
/*#undef HAS_XCB */

/* Define to 1 if Xlib's xrender is available */
#define HAS_XRENDER 0

/* Define to 1 if popen(3) is available */
#define HAS_POPEN 0

/* Define to 1 if popen(3) is not available but fork(2) and pipe(2) are available */
/*#undef HAS_PIPE */

#define USER_CONF_DIR        "userConf"

/* Extra includes required by the detected libs (may be empty): */

#define _XOPEN_SOURCE


