/*************************************************************/
/* Generated by scconfig - DO NOT EDIT - will be overwritten */
/* Source: config.h.in; to regenerate run ./configure        */
/*************************************************************/

/* Define to 1 if cairo is available and is to be used */
/*#undef HAS_CAIRO */

/* Define to 1 if Xlib's xcb is available */
/*#undef HAS_XCB */

/* Define to 1 if Xlib's xrender is available */
#define HAS_XRENDER 1

/* Define to 1 if popen(3) is available */
#define HAS_POPEN 0

/* Define to 1 if popen(3) is not available but fork(2) and pipe(2) are available */
/*#undef HAS_PIPE */

#ifndef XSCHEM_LIBRARY_PATH
#define XSCHEM_LIBRARY_PATH  "C:/Program Files/XSchem/xschem_library;C:/Program Files/XSchem/xschem_library/devices;C:/Program Files/XSchem/xschem_library/examples;C:/Program Files/XSchem/xschem_library/ngspice;C:/Program Files/XSchem/xschem_library/logic;C:/Program Files/XSchem/xschem_library/binto7seg;C:/Program Files/XSchem/xschem_library/pcb;C:/Program Files/XSchem/xschem_library/rom8k"
#endif
#define USER_CONF_DIR        "userConf"

/* Extra includes required by the detected libs (may be empty): */

#define _XOPEN_SOURCE


